#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
apt-get -y update
apt-get -y install nginx

# Remove default Nginx configuration
sudo rm /etc/nginx/sites-enabled/default

# Create new Nginx configuration
sudo touch /etc/nginx/sites-available/custom
sudo ln -s /etc/nginx/sites-available/custom /etc/nginx/sites-enabled/custom

# Edit Nginx configuration file
sudo bash -c 'cat > /etc/nginx/sites-available/custom << EOL
server {
  listen 80 default_server;
  listen [::]:80 default_server;

  server_name _;

  # Add custom header to HTTP response
  add_header X-Served-By $hostname;

  # Serve web content
  root /var/www/html;
  index index.html;

  location / {
    try_files $uri $uri/ =404;
  }
}
EOL'

# Restart Nginx to apply configuration
sudo systemctl restart nginx
